[package]
authors = ["idlescreen developers"]
repository = "https://github.com/idlescreen/idlescreen"
name = "idle-ipc"
version = "0.5.0"
edition = "2024"
description = "Out-of-process screensaver execution and shared memory IPC"
license = "Apache-2.0"

[dependencies]
libc = { workspace = true }
idle-api = { path = "../../idle-api" }

[dev-dependencies]
